"""all tables

Revision ID: dec9f53f15bf
Revises: 
Create Date: 2019-01-05 14:53:33.659595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec9f53f15bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fasttext_neighbors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grapheme', sa.String(), nullable=True),
    sa.Column('neighbors', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fasttext_neighbors_grapheme'), 'fasttext_neighbors', ['grapheme'], unique=True)
    op.create_table('fasttext_vectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grapheme', sa.String(), nullable=True),
    sa.Column('v1', sa.Float(), nullable=True),
    sa.Column('v2', sa.Float(), nullable=True),
    sa.Column('v3', sa.Float(), nullable=True),
    sa.Column('v4', sa.Float(), nullable=True),
    sa.Column('v5', sa.Float(), nullable=True),
    sa.Column('v6', sa.Float(), nullable=True),
    sa.Column('v7', sa.Float(), nullable=True),
    sa.Column('v8', sa.Float(), nullable=True),
    sa.Column('v9', sa.Float(), nullable=True),
    sa.Column('v10', sa.Float(), nullable=True),
    sa.Column('v11', sa.Float(), nullable=True),
    sa.Column('v12', sa.Float(), nullable=True),
    sa.Column('v13', sa.Float(), nullable=True),
    sa.Column('v14', sa.Float(), nullable=True),
    sa.Column('v15', sa.Float(), nullable=True),
    sa.Column('v16', sa.Float(), nullable=True),
    sa.Column('v17', sa.Float(), nullable=True),
    sa.Column('v18', sa.Float(), nullable=True),
    sa.Column('v19', sa.Float(), nullable=True),
    sa.Column('v20', sa.Float(), nullable=True),
    sa.Column('v21', sa.Float(), nullable=True),
    sa.Column('v22', sa.Float(), nullable=True),
    sa.Column('v23', sa.Float(), nullable=True),
    sa.Column('v24', sa.Float(), nullable=True),
    sa.Column('v25', sa.Float(), nullable=True),
    sa.Column('v26', sa.Float(), nullable=True),
    sa.Column('v27', sa.Float(), nullable=True),
    sa.Column('v28', sa.Float(), nullable=True),
    sa.Column('v29', sa.Float(), nullable=True),
    sa.Column('v30', sa.Float(), nullable=True),
    sa.Column('v31', sa.Float(), nullable=True),
    sa.Column('v32', sa.Float(), nullable=True),
    sa.Column('v33', sa.Float(), nullable=True),
    sa.Column('v34', sa.Float(), nullable=True),
    sa.Column('v35', sa.Float(), nullable=True),
    sa.Column('v36', sa.Float(), nullable=True),
    sa.Column('v37', sa.Float(), nullable=True),
    sa.Column('v38', sa.Float(), nullable=True),
    sa.Column('v39', sa.Float(), nullable=True),
    sa.Column('v40', sa.Float(), nullable=True),
    sa.Column('v41', sa.Float(), nullable=True),
    sa.Column('v42', sa.Float(), nullable=True),
    sa.Column('v43', sa.Float(), nullable=True),
    sa.Column('v44', sa.Float(), nullable=True),
    sa.Column('v45', sa.Float(), nullable=True),
    sa.Column('v46', sa.Float(), nullable=True),
    sa.Column('v47', sa.Float(), nullable=True),
    sa.Column('v48', sa.Float(), nullable=True),
    sa.Column('v49', sa.Float(), nullable=True),
    sa.Column('v50', sa.Float(), nullable=True),
    sa.Column('v51', sa.Float(), nullable=True),
    sa.Column('v52', sa.Float(), nullable=True),
    sa.Column('v53', sa.Float(), nullable=True),
    sa.Column('v54', sa.Float(), nullable=True),
    sa.Column('v55', sa.Float(), nullable=True),
    sa.Column('v56', sa.Float(), nullable=True),
    sa.Column('v57', sa.Float(), nullable=True),
    sa.Column('v58', sa.Float(), nullable=True),
    sa.Column('v59', sa.Float(), nullable=True),
    sa.Column('v60', sa.Float(), nullable=True),
    sa.Column('v61', sa.Float(), nullable=True),
    sa.Column('v62', sa.Float(), nullable=True),
    sa.Column('v63', sa.Float(), nullable=True),
    sa.Column('v64', sa.Float(), nullable=True),
    sa.Column('v65', sa.Float(), nullable=True),
    sa.Column('v66', sa.Float(), nullable=True),
    sa.Column('v67', sa.Float(), nullable=True),
    sa.Column('v68', sa.Float(), nullable=True),
    sa.Column('v69', sa.Float(), nullable=True),
    sa.Column('v70', sa.Float(), nullable=True),
    sa.Column('v71', sa.Float(), nullable=True),
    sa.Column('v72', sa.Float(), nullable=True),
    sa.Column('v73', sa.Float(), nullable=True),
    sa.Column('v74', sa.Float(), nullable=True),
    sa.Column('v75', sa.Float(), nullable=True),
    sa.Column('v76', sa.Float(), nullable=True),
    sa.Column('v77', sa.Float(), nullable=True),
    sa.Column('v78', sa.Float(), nullable=True),
    sa.Column('v79', sa.Float(), nullable=True),
    sa.Column('v80', sa.Float(), nullable=True),
    sa.Column('v81', sa.Float(), nullable=True),
    sa.Column('v82', sa.Float(), nullable=True),
    sa.Column('v83', sa.Float(), nullable=True),
    sa.Column('v84', sa.Float(), nullable=True),
    sa.Column('v85', sa.Float(), nullable=True),
    sa.Column('v86', sa.Float(), nullable=True),
    sa.Column('v87', sa.Float(), nullable=True),
    sa.Column('v88', sa.Float(), nullable=True),
    sa.Column('v89', sa.Float(), nullable=True),
    sa.Column('v90', sa.Float(), nullable=True),
    sa.Column('v91', sa.Float(), nullable=True),
    sa.Column('v92', sa.Float(), nullable=True),
    sa.Column('v93', sa.Float(), nullable=True),
    sa.Column('v94', sa.Float(), nullable=True),
    sa.Column('v95', sa.Float(), nullable=True),
    sa.Column('v96', sa.Float(), nullable=True),
    sa.Column('v97', sa.Float(), nullable=True),
    sa.Column('v98', sa.Float(), nullable=True),
    sa.Column('v99', sa.Float(), nullable=True),
    sa.Column('v100', sa.Float(), nullable=True),
    sa.Column('v101', sa.Float(), nullable=True),
    sa.Column('v102', sa.Float(), nullable=True),
    sa.Column('v103', sa.Float(), nullable=True),
    sa.Column('v104', sa.Float(), nullable=True),
    sa.Column('v105', sa.Float(), nullable=True),
    sa.Column('v106', sa.Float(), nullable=True),
    sa.Column('v107', sa.Float(), nullable=True),
    sa.Column('v108', sa.Float(), nullable=True),
    sa.Column('v109', sa.Float(), nullable=True),
    sa.Column('v110', sa.Float(), nullable=True),
    sa.Column('v111', sa.Float(), nullable=True),
    sa.Column('v112', sa.Float(), nullable=True),
    sa.Column('v113', sa.Float(), nullable=True),
    sa.Column('v114', sa.Float(), nullable=True),
    sa.Column('v115', sa.Float(), nullable=True),
    sa.Column('v116', sa.Float(), nullable=True),
    sa.Column('v117', sa.Float(), nullable=True),
    sa.Column('v118', sa.Float(), nullable=True),
    sa.Column('v119', sa.Float(), nullable=True),
    sa.Column('v120', sa.Float(), nullable=True),
    sa.Column('v121', sa.Float(), nullable=True),
    sa.Column('v122', sa.Float(), nullable=True),
    sa.Column('v123', sa.Float(), nullable=True),
    sa.Column('v124', sa.Float(), nullable=True),
    sa.Column('v125', sa.Float(), nullable=True),
    sa.Column('v126', sa.Float(), nullable=True),
    sa.Column('v127', sa.Float(), nullable=True),
    sa.Column('v128', sa.Float(), nullable=True),
    sa.Column('v129', sa.Float(), nullable=True),
    sa.Column('v130', sa.Float(), nullable=True),
    sa.Column('v131', sa.Float(), nullable=True),
    sa.Column('v132', sa.Float(), nullable=True),
    sa.Column('v133', sa.Float(), nullable=True),
    sa.Column('v134', sa.Float(), nullable=True),
    sa.Column('v135', sa.Float(), nullable=True),
    sa.Column('v136', sa.Float(), nullable=True),
    sa.Column('v137', sa.Float(), nullable=True),
    sa.Column('v138', sa.Float(), nullable=True),
    sa.Column('v139', sa.Float(), nullable=True),
    sa.Column('v140', sa.Float(), nullable=True),
    sa.Column('v141', sa.Float(), nullable=True),
    sa.Column('v142', sa.Float(), nullable=True),
    sa.Column('v143', sa.Float(), nullable=True),
    sa.Column('v144', sa.Float(), nullable=True),
    sa.Column('v145', sa.Float(), nullable=True),
    sa.Column('v146', sa.Float(), nullable=True),
    sa.Column('v147', sa.Float(), nullable=True),
    sa.Column('v148', sa.Float(), nullable=True),
    sa.Column('v149', sa.Float(), nullable=True),
    sa.Column('v150', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fasttext_vectors_grapheme'), 'fasttext_vectors', ['grapheme'], unique=True)
    op.create_table('subgrapheme_frequencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grapheme', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('frequency_head', sa.Integer(), nullable=True),
    sa.Column('frequency_tail', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subgrapheme_frequencies_grapheme'), 'subgrapheme_frequencies', ['grapheme'], unique=True)
    op.create_table('subphoneme_frequencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phoneme', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('frequency_head', sa.Integer(), nullable=True),
    sa.Column('frequency_tail', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subphoneme_frequencies_phoneme'), 'subphoneme_frequencies', ['phoneme'], unique=True)
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grapheme', sa.String(), nullable=True),
    sa.Column('phoneme', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('grapheme_chunks', sa.JSON(), nullable=True),
    sa.Column('phoneme_chunks', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    op.drop_index(op.f('ix_subphoneme_frequencies_phoneme'), table_name='subphoneme_frequencies')
    op.drop_table('subphoneme_frequencies')
    op.drop_index(op.f('ix_subgrapheme_frequencies_grapheme'), table_name='subgrapheme_frequencies')
    op.drop_table('subgrapheme_frequencies')
    op.drop_index(op.f('ix_fasttext_vectors_grapheme'), table_name='fasttext_vectors')
    op.drop_table('fasttext_vectors')
    op.drop_index(op.f('ix_fasttext_neighbors_grapheme'), table_name='fasttext_neighbors')
    op.drop_table('fasttext_neighbors')
    # ### end Alembic commands ###
